[workspace]
resolver = "3"
members = ["crates/parakeet-audio", "crates/parakeet-proto", "crates/parakeet-server", "crates/parakeet-type"]

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "MIT"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
parakeet-proto = { path = "crates/parakeet-proto" }
parakeet-audio = { path = "crates/parakeet-audio" }
