#!/usr/bin/env bash
# Build SyrinxCore.xcframework for iOS device and simulator.
#
# Run on macOS with Xcode installed. Linux can `cargo check` these targets --
# useful for catching Rust errors fast -- but cannot link them: ring compiles C
# and assembly that needs the iOS SDK.
set -euo pipefail
cd "$(dirname "$0")"
ROOT="$(cd ../.. && pwd)"
OUT="${1:-$ROOT/target/SyrinxCore.xcframework}"

for t in aarch64-apple-ios aarch64-apple-ios-sim; do
    echo "building $t"
    (cd "$ROOT" && cargo build --release --target "$t" -p syrinx-ios)
done

# The header is written here rather than kept as a file so it cannot drift
# from lib.rs without someone noticing the diff.
INC="$(mktemp -d)/include"
mkdir -p "$INC"
cat > "$INC/syrinx.h" <<'HEADER'
// Generated by build-xcframework.sh. Mirrors crates/syrinx-ios/src/lib.rs.
#ifndef SYRINX_H
#define SYRINX_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

typedef struct SyrinxSession SyrinxSession;

// 0 idle, 1 connecting, 2 listening, 3 stopping, 4 transcribing
typedef int32_t SyrinxStatus;

// NULL if url or token are not valid UTF-8. Connecting happens
// asynchronously: a non-NULL return means "starting", not "connected".
SyrinxSession *syrinx_start(const char *url, const char *token);

// 16 kHz mono. false if the session ended or the queue is full; drop the
// buffer rather than block, this is called from an audio thread.
bool syrinx_push_audio(SyrinxSession *session, const float *samples, size_t len);

// Transcript text not yet handed over, or NULL. Free with syrinx_string_free.
// Text is delivered once and never repeated.
char *syrinx_take_text(SyrinxSession *session);

SyrinxStatus syrinx_status(SyrinxSession *session);

// Error text or NULL. Free with syrinx_string_free.
char *syrinx_take_error(SyrinxSession *session);

// Stops and frees. The pointer is invalid afterwards.
void syrinx_stop(SyrinxSession *session);

void syrinx_string_free(char *s);
const char *syrinx_version(void);
uint32_t syrinx_sample_rate(void);

#endif
HEADER
cat > "$INC/module.modulemap" <<'MODMAP'
module SyrinxCore {
    header "syrinx.h"
    export *
}
MODMAP

rm -rf "$OUT"
xcodebuild -create-xcframework \
    -library "$ROOT/target/aarch64-apple-ios/release/libsyrinx_ios.a"     -headers "$INC" \
    -library "$ROOT/target/aarch64-apple-ios-sim/release/libsyrinx_ios.a" -headers "$INC" \
    -output "$OUT"

echo
echo "$OUT"
nm -gU "$OUT/ios-arm64/libsyrinx_ios.a" 2>/dev/null | grep -E " T _syrinx_" | awk '{print "  " $3}'
