[package]
name = "syrinx-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "syrinx"
path = "src/main.rs"

[dependencies]
toml = "0.9"
syrinx-audio.workspace = true
syrinx-client.workspace = true
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap = { version = "4", features = ["derive"] }
